### ISSUE TITLE
Support to signing XMLs using smartcards

### ISSUE THREAD

**Issue by ldnunes** [kislyuk/signxml#10]
Is there support for signing XML using smartcards? If not, is there any plans to do so in the future?

Thanks.

**Comment by kislyuk** [comment]
I have no clue what this means because I've never worked with smartcards before. If you give me some details on the relevant protocols, I may be able to comment more.

**Comment by ldnunes** [comment]
@kislyuk Thanks for the reply.

It would probably involve using a PKCS #11 Python library like [PyKCS11](https://bitbucket.org/gambit4id/pykcs11). With this we can use a cryptographic token like a smart card to pass the private key representation object to the sign method. I think this may be possible by creating a new [Cryptography backend interface](https://cryptography.io/en/latest/hazmat/backends/interfaces/) that maps the PKCS #11 library and smartcard to the Cryptography backend that signxml defines.

I asked if anyone had already done something like it to signxml to see if it is feasible to change such core components. Any comments on this? Specifically on the part that requires changing the Cryptography backend to a new one. Thanks again!

**Comment by ldnunes** [comment]
My company was able to solve this creating a OpenSSL engine that intercepts the signatures requests and then sends them directly to the smart card.

I'll close the issue.
