### ISSUE TITLE
ascii codec can't decode byte 0xC2 in position 59: ordinal not in range (128)

### ISSUE THREAD

**Issue by nick210** [kislyuk/signxml#18]
Dear all,

I am trying to validate an xml signature (saml token) using signxml.
I am using the following code:

cert=open("/path_to_pem_file").read()
root=ElementTree.fromstring(saml_xml_token)
assertion_data=xmldsig(root)verify(x509_cert=cert)

And the last command     xmldsig(root)verify(x509_cert=cert)  gives me the following error:
ascii codec can't decode byte 0xC2 in position 59: ordinal not in range (128)

I have tried using  reload(sys)
                           sys.setdefaultencoding('utf-8')
but with no result.

Do you have any idea what could be wrong with the code?

Thank you,
Nick

**Comment by kislyuk** [comment]
Please paste a complete stack trace.

**Comment by nick210** [comment]
The stack trace is the following:

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
 202.       assertion_data=xmldsig(autho).verify(x509_cert=cert)
File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py" in verify
  577.             _get_schema().assertValid(signature)
File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py" in _get_schema
  79.             _schema = etree.XMLSchema(etree.parse(fh))
File "/usr/lib/python2.7/encodings/ascii.py" in decode
  26.         return codecs.ascii_decode(input, self.errors)[0]

Exception Type: UnicodeDecodeError at /model_app/trySaml/
Exception Value: &#39;ascii&#39; codec can&#39;t decode byte 0xc2 in position 59: ordinal not in range(128)

Any idea?

**Comment by kislyuk** [comment]
Thank you for reporting. This was a bug in how SignXML handled the schema file. Fixed in v0.4.3, please test.
