### ISSUE TITLE
Enveloped signature with no (or empty) reference URI

### ISSUE THREAD

**Issue by viclevy** [kislyuk/signxml#20]
Hi Andrey,

Some SaaS providers supporting SSO using SAML may reject signed assertion if enveloped signature has no (or empty) reference URI. 

I'd like to suggest the following enhancement to the enveloped signature functionality which will look for and specify the reference URI based on the signed data id attribute value.

signxml/signxml/__init__.py:
```
210              raise InvalidInput("Enveloped signature input contains more than one placeholder")
211
212        self._reference_uri = ""
+++        # get signed data id attribute value for reference uri  
+++        payloadId = self.payload.get("Id", self.payload.get("ID"))
+++        if payloadId is not None:
+++            # set default reference uri based on data id attribute value
+++            self._reference_uri = "#{}".format(payloadId)
213        elif method == methods.detached:
214            if self._reference_uri is None:
215                self._reference_uri = "#{}".format(self.payload.get("Id", self.payload.get("ID", "object")))

```
Regards,
Vic.

**Comment by kislyuk** [comment]
Thanks Vic, this sounds reasonable, although I haven't looked thoroughly into how this modifies the current behavior yet.

To start, could you please open a pull request with this change? You can simply navigate to https://github.com/kislyuk/signxml/blob/master/signxml/__init__.py, click the edit button on the top right, paste your changes, and open the PR from there.

**Comment by viclevy** [comment]
Done.

Thanks,
Vic.

**Comment by kislyuk** [comment]
It appears that you never actually opened the pull request.

**Comment by kislyuk** [comment]
I think you meant to click the green button here: https://github.com/kislyuk/signxml/compare/master...viclevy:patch-1?expand=1

**Comment by viclevy** [comment]
Future release will include a fix for this - closing this issue.

Thank you,
Vic.
