### ISSUE TITLE
xml.etree.ElementTree nodes

### ISSUE THREAD

**Issue by nickcash** [kislyuk/signxml#23]
The change made for issue #19 may not be 100% yet. There's a slight difference in behaviour: using sign() on an lxml etree node modifies it in-place, whereas using it on a stdlib etree node returns a new signed copy but doesn't modify the original.
I don't see the docs specifically make a promise to sign in-place, but the very first example (signing and then verifying) relies on it.

To build from my previous test case:
```
x = "<foo><bar></bar></foo>"
root1=xml.etree.ElementTree.fromstring(x)
root2=lxml.etree.fromstring(x)

signxml.xmldsig(root1).sign(key=key, cert=cert)
signxml.xmldsig(root2).sign(key=key, cert=cert)

>>>signxml.xmldsig(root1).verify()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 580, in verify
    signature = self._find(root, "Signature")
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 663, in _find
    raise InvalidInput("Expected to find XML element {} in {}".format(query, element.tag))
signxml.InvalidInput: Expected to find XML element Signature in foo
#no good! 

>>>signxml.xmldsig(root2).verify()
<Element foo at 0x7fb4d8c9ca28>
#okay!


#But....
root1 = signxml.xmldsig(root1).sign(key=key, cert=cert)
>>>signxml.xmldsig(root1).verify()
<Element foo at 0x7fb4d8ca0560>
#this actually works!
```

**Comment by kislyuk** [comment]
I have altered the docs. Pray I don't alter them further :)

Thanks for spotting this, @nickcash. Let me know if you see any further inconsistencies.

**Comment by kislyuk** [comment]
(I agree in principle it would be good to have the behavior be consistent, but I can't be bothered to figure out how at this moment. PRs welcome.)
