### ISSUE TITLE
X509Certificate filled not according to spec

### ISSUE THREAD

**Issue by ashemedai** [kislyuk/signxml#26]
Currently the ds:X509Certificate element gets filled from OpenSSL.crypto.dump_certificate(), but the problem here is that it also adds headers and footers like `-----BEGIN PUBLIC KEY-----`. This is not allowed by the XMLDSig specification. Reading e.g. http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/#sec-X509Data or http://www.w3.org/TR/xmldsig-core2/#sec-X509Data you note that:

* The X509Certificate element, which contains a base64-encoded [X509v3] certificate
* The schema has: `<element name="X509Certificate" type="base64Binary"/>`
* All the examples start immediately with MII...
* base64Binary disallows the `-`

Relevant line is 399 in `__init__.py`. Looking at how to resolve this.

**Comment by ashemedai** [comment]
Current workaround:

Adjust `__init__.py` with `x509_certificate.text = strip_pem_header(dump_certificate(FILETYPE_PEM, cert))`.

Adjust `util/__init__.py` with:

`PEM_PUBLIC_KEY_HEADER = "-----BEGIN PUBLIC KEY-----"
PEM_PUBLIC_KEY_FOOTER = "-----END PUBLIC KEY-----"

if line != PEM_HEADER and line != PEM_FOOTER and line != PEM_PUBLIC_KEY_HEADER and line != PEM_PUBLIC_KEY_FOOTER:`

Things I still don't understand is why I am triggering the OpenSSL dump in the first place.

**Comment by kislyuk** [comment]
Could you give me the format of your call to `sign()`? You are probably triggering the dump because you're passing a cert to it. If you don't want to have the cert inserted into the signed XML, you should be able to avoid it by not passing the cert.

It appears the relevant line of code (dump_certificate) is not covered by any of the tests. I'll need to correct that, and I trust that your fix is the right one (i.e. PEM headers/footers need to be stripped). Feel free to open a PR for this change, but it will have to come with a test in the test suite.

**Comment by ashemedai** [comment]
Sorry, was writing an update and got called away to meetings.

Yes, it looks like I had a bad export of the public certificate as a public key that might have triggered it. It was in `-----BEGIN PUBLIC KEY-----` format. Using a proper export as a `-----BEGIN CERTIFICATE-----` solved my issue at least. 

Stupid, actually, because there's no use case for just putting the public key in the X509Certificate section, because that doesn't allow any verification by the receiving party that way. 

So I think in this case it was a brainfart on my side. I can definitely look at the testing of that section of code when I come back from vacation in about a wek.

**Comment by kislyuk** [comment]
It looks like some sanity check somewhere would have made this easier, but I'm not sure what. Let me know if you can suggest one.
