### ISSUE TITLE
Set Reference URI and add a transform algorithm

### ISSUE THREAD

**Issue by danimaribeiro** [kislyuk/signxml#3]
I've been using C# to generate a signed xml and I got something like this:
![this is what i need](https://cloud.githubusercontent.com/assets/854781/4993657/7adc96fc-6998-11e4-993a-67042a05fe13.PNG)

I can set the URI in reference, and also I have two transform algorithm (I have no idea what is used for)
The closest I got is this:
![generated signatura](https://cloud.githubusercontent.com/assets/854781/4993660/7feb0bec-6998-11e4-88ae-f6fe602b9360.PNG)

I tried with Signature placeholder, but couldn't find a way to change the URI.

Could you help me on this? Thanks.

**Comment by kislyuk** [comment]
You can now specify the reference URI when generating the signature with `xmldsig(root).sign(reference_uri="#NFe42140903657739000169550020000000011000000011")`.

**Comment by danimaribeiro** [comment]
Thanks for the change, I didn't notice before.
I'll make some tests with it. Sorry not to send a PR with the changes, crypto is not my strongest.

**Comment by leotada** [comment]
Hello, I need this too, and my test here didn't work.
signer.sign(method=signxml.methods.enveloped, key=key, cert=cert,
                   algorithm="rsa-sha1",
                   c14n_algorithm='http://www.w3.org/TR/2001/REC-xml-c14n-20010315',    
                   reference_uri='#NFe42140903657739000169550020000000011000000011') 

I have noted that line 208 in __init__.py:
    self._reference_uri = ""
https://github.com/kislyuk/signxml/blob/master/signxml/__init__.py#L208

**Comment by kislyuk** [comment]
That line is not involved in signing, only in verification.

Please provide the complete payload that you're trying to sign, and the full error output. You can email it to me.

**Comment by leotada** [comment]
Did not happen error, only not work, the output URI is empty:  URI=""
I changed here and work, I will send pull request to you see.

**Comment by leotada** [comment]
https://github.com/kislyuk/signxml/pull/17
