### ISSUE TITLE
Support custom reference URI for enveloped

### ISSUE THREAD

**Issue by pnegry** [kislyuk/signxml#31]
I'm interoping with a WSTrust endpoint, that has a Reference URI defined even though the transform is enveloped.

Therefore, I patched the following line:

`self._reference_uri = ""`
to:
```
if self._reference_uri == None:
    self._reference_uri = ""
```

**Comment by kislyuk** [comment]
Thanks. Can you open a PR and provide a test case?

**Comment by pnegry** [comment]
No sorry, I'm already done with it.
