### ISSUE TITLE
validation against custom CA

### ISSUE THREAD

**Issue by rhoerbe** [kislyuk/signxml#41]
I need to validate signatures against a project-specific CA. I tried:

cert file: signxml.xmldsig(xml_bytes).verify(ca_pem_file=mycacert.pem)
This raises OpenSSL.crypto.X509StoreContextError: [18, 0, 'self signed certificate']

    Traceback: 
      [..]/signxml/__init__.py", line 694, in verify_x509_cert_chain
        X509StoreContext(store, cert).verify_certificate()
      [..]/crypto.py, line 1571, in verify_certificate
        raise self._exception_from_context()
 
cert dir: signxml.xmldsig(xml_bytes).verify(ca_path=mycadir)
this raises AttributeError: 'NoneType' object has no attribute 'encode'. I think that it is a bug, because ensure_bytes() does not allow None arguments.

     Traceback: 
       [..]/signxml/__init__.py", line 690, in verify_x509_cert_chain
         context.load_verify_locations(ensure_bytes(ca_pem_file), capath=ca_path)
       [..]/signxml/util/__init__.py", line 20, in ensure_bytes
         x = x.encode(encoding)

Aslo, what would be a reliable method to obtain the signing certificate? I need to check certs against a list of allowed signers.

**Comment by kislyuk** [comment]
Thank you for reporting. To your bug report, I agree that's a bug, and it should be fixed with https://github.com/kislyuk/signxml/commit/6639a42a03b9008cbb24f1f26fd14d1e328e8b32 (the test is a bit harder than usual so it's not in the test suite yet).

To your question, short of trying against each signer certificate with `xmldsig(xml).verify(x509_cert=...)` (iterating over them all) there is no good way to do this yet. Ideally you would be able to recover the signature node as well as the payload from the verification process, and then examine the signature node yourself, or you could imagine a protocol for extending the base class to insert your own verification middlewares.

The verify method itself extracts the signature like this:

```
signature = self._find(root, "Signature", anywhere=True)
...
x509_data = signature.find("ds:KeyInfo/ds:X509Data", namespaces=namespaces)
```

So you could do that yourself, but ultimately returning the relevant data or having a custom verifier extension mechanism should be the library's responsibility.

**Comment by rhoerbe** [comment]
If I use an xpath expression to search for the signer certificate I might be vulnerable to the flexibility of xmldsig. Should'nt the see-what-you-sign principle be use in analogy to see-who-signed? Just thinking of the example of nested signatures in SAML for Response/Assertion, what take precedence? The outermost or first occurrence? I guess that it would be wise if verify() would not only return the verified xml, but the signature certificate(s) vouching for this as well. To cover the nested signature case of SAML, the return value would have to list return values by URI as well.

**Comment by mmaschenk** [comment]
I second the enhancement proposed by rhoerbe above: verify should somehow also return the signing signature(s). I have the use case where I do not only want to know that the CA validates, but also which certificate corresponds to the actual signature...

**Comment by kislyuk** [comment]
That is a great idea, but I'm unlikely to be able to do it in the next few weeks. PRs welcome.

**Comment by klondi** [comment]
@kislyuk I can get the problem  @mmaschenk fixed but it involved changes to the API so the signature node can be returned. What do you propose doing for this?

**Comment by kislyuk** [comment]
@klondi thanks for the offer. I'm fine with changing the signature of `verify()` to return a VerifyResult, something like
```
class VerifyResult(namedtuple("signed_xml signature_xml")):
     pass
...
return VerifyResult(signed, sig_root)
```

**Comment by klondi** [comment]
@kislyuk roger I'll fix it today and send you a pull request fixing this and #47 then

**Comment by kislyuk** [comment]
This should be fixed now. @rhoerbe, please test against the most recent release (v1.0.0).

**Comment by rhoerbe** [comment]
coming back to testing this 2 months later ..

I run into a problem with DigestValidation:
/Users/admin/virtualenvs/pvzd34/lib/python3.4/site-packages/signxml-1.0.0-py3.4.egg/signxml/__init__.py", line 707, in verify
    raise InvalidDigest("Digest mismatch")

Using this code:
```
import base64, lxml.etree, signxml
md_dom = lxml.etree.parse('metadata.xml')
md_root = md_dom.getroot()
with open('metadata_crt.pem', 'r') as fd:
    md_cert_pem = fd.read()
asserted_metadata = signxml.xmldsig(md_root).verify(x509_cert=md_cert_pem)
```
on the attached data files.

However, I believe that the signature is valid, because I am signing this with the pyff tool, which is not know of having this problem, and I verified the signature also with Shibboleth xmlsectool (v2 beta-2):

    xmlsectool.sh --inFile metadata.xml --certificate metadata_crt.pem --whitelistDigest SHA-1 --verifySignature

Remark: given that the documentation of this nice library is fairly spare, I suggest to include my code example in the README.

**Comment by kislyuk** [comment]
So far I don't know what's going wrong here. The signature verifies fine, but as you can see, there is a digest mismatch. This almost certainly means the content canonicalization method is producing different results in shibboleth vs. signxml. I also took your data and ran it through the xmlsec verifier (https://www.aleksey.com/xmlsec/xmldsig-verifier.html) and xml-crypto (https://github.com/yaronn/xml-crypto). Both failed to verify the digest, but for different reasons.

There are several obscure issues (signature node whitespace excision, character encoding, inclusive namespace prefix list) that can affect canonicalization and lead to this error. To move forward, I need the byte string that xmlsectool considers the canonicalization for the digest, so I can diff it against ours. I can't find the source for xmlsectool though, so I'm stuck.

**Comment by kislyuk** [comment]
I took a look at the library that you are using to sign your XML (https://github.com/leifj/pyXMLSecurity, used by pyff) and found the problem. The digest mismatch issue that you experienced is due to a bug in pyXMLSecurity. Specifically, pyXMLSecurity incorrectly handles canonicalization. The payload canonicalization transform in the signature that you attached is `<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#WithComments"/>`. `WithComments` indicates that XML comments are not excised from the bytestring that is fed to the digest function. However, pyXMLSecurity does excise the comments when digesting the data for signing. This could be because it confuses the value of `CanonicalizationMethod` (`<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>`) used to digest the signature with the value of `ds:Transform` above used to digest the payload.

**Comment by rhoerbe** [comment]
Thanks, I will follow up in pyXMLSecurity.

**Comment by kislyuk** [comment]
I've traced this to https://github.com/leifj/pyXMLSecurity/blob/master/src/xmlsec/__init__.py#L230: the parse_xml method used there appears to always excise comments, regardless of the value of `with_comments`.

**Comment by leifj** [comment]
Can any of you guys give me a simple testcase - a bit of xml that pyXMLSecurity fails to sign or verify and how to reproduce this.

**Comment by kislyuk** [comment]
@leifj: I ran the following on the file that @rhoerbe attached:
```
python -c'from lxml import etree; import xmlsec; xmlsec.verify(etree.fromstring(open("07/metadata.xml").read()), "07/metadata_crt.pem")'
```
It verifies successfully, and signxml reports a digest mismatch. When I compared the canonicalization of the digest input between the two, I found that yours omits comments. But the canonicalization transform is `<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#WithComments"/>`.

**Comment by rhoerbe** [comment]
The problem is with the configuration: The handling of comments depends on the setting of c14n_strip_ws, not of the selected c14n algorithm.

**Comment by kislyuk** [comment]
If this configuration causes the library to generate and incorrectly verify an invalid signature, then my suggestion would be to change the logic to preclude that possibility.

**Comment by leifj** [comment]
I understand the logic & reasoning. Could you just point to where the testcase xml lives - you refer to "07/metadata.xml"... If possible open an issue over in pyXMLSecurity with this xml attached. Thx.

**Comment by kislyuk** [comment]
@leifj sorry if I wasn't clear - it's attached in one of the comments above - https://github.com/kislyuk/signxml/files/333766/metadata_test_07.zip

**Comment by leifj** [comment]
Excellent. Thx!

I'll work on it asap. I don't think its related to the parse argument - that is mostly there to work around some broken xmlsig implementations and is very rarely used. It is much more likely that I'm picking the wrong c14n method somewhere (as you pointed out) possibly getting envelope and transformation mixed up.

**Comment by leifj** [comment]
Gettig back to this after vacation etc... how was the "07" example created? I'm assuming using some other tool than pyXMLSecurity?

**Comment by leifj** [comment]
I'm trying to create a testcase (that should fail currently) for this issue and was wondering which tool you used to create the "07" example?

**Comment by klondi** [comment]
@leifj mentions may work better: i.e. @rhoerbe

**Comment by leifj** [comment]
So I created a testcase in pyXMLSecurity@7802e34561cde01950c1d50c781009a6b3efc5cb based on the "07" example and right now pyXMLSecurity can successfully verify that signature wo applying any of the modifications @rhoerbe suggested in his PR. 

I'm a bit stumped.

**Comment by leifj** [comment]
So to be precise - I need to understand which tool you used that couldn't verify that 07 xml so I can incorporate in a testcase and start to figure out what is going on.

**Comment by leifj** [comment]
ping @rhoerbe @klondi

**Comment by rhoerbe** [comment]
IIRC this was the last beta version of shib xmlsectool V2. I have only limited access to my working resources until 19. Sept.
