### ISSUE TITLE
Update cryptography dependency to cryptography>=1.1.2

### ISSUE THREAD

**Issue by iwnijao** [kislyuk/signxml#45]
As I see, signxml depends on cryptography<1.1,>=1.0.2 but cryptography<1.1.2 has a runtime error [undefined symbol EC_GFp_nistp224_method](https://cryptography.io/en/latest/changelog/#id4) with some OpenSSL installations.

I'm trying to run signxml (pip install signxml) on Fedora 23 and I'm getting undefined symbol EC_GFp_nistp224_method runtime error from cryptography library. I updated cryptography to v1.2.3 (pip install --upgrade cryptography) and everything is working fine so far.

**Comment by kislyuk** [comment]
Should be fixed in v0.5.0, please test.
