### ISSUE TITLE
Signature nodes should be removed from the returned payload on verify()

### ISSUE THREAD

**Issue by klondi** [kislyuk/signxml#47]
When doing a verify() the payload returned contains the signature nodes. As these nodes have to be removed before generating the hash (At least for enveloped signatures) this means that any nodes inserted on the signature might be considered valid despite not being so which opens the risk for accepting unsigned data as valid.

I can submit a patch to this issue later if #46 is merged.

**Comment by kislyuk** [comment]
Great idea to remove unsigned data from verify() output, thanks for implementing.

**Comment by klondi** [comment]
My pleasure!
