### ISSUE TITLE
xml:id isn't accepted as a valid id_attribute

### ISSUE THREAD

**Issue by nbastin** [kislyuk/signxml#48]
If I have a signed document, with the proper reference element as:

```
 <Reference URI="#ref846526240431F74B">
```

And a matching element in the document:
```
<credential xml:id="ref846526240431F74B">
```

This isn't found, because `xml:id` isn't a valid `id_attribute` searched by `_resolve_reference`:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 636, in verify
    payload = self._resolve_reference(root, reference, uri_resolver=uri_resolver)
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 498, in _resolve_reference
    raise InvalidInput("Unable to resolve reference URI: {}".format(uri))
InvalidInput: Unable to resolve reference URI: #ref846526240431F74B
```

**Comment by kislyuk** [comment]
This has something to do with handling the implicit `xml:` namespace, but I'm not sure exactly how. This is the relevant xpath expression used to locate the element (https://github.com/kislyuk/signxml/blob/master/signxml/__init__.py#L493):
```python
results = doc_root.xpath("..//*[@{}=$uri]".format(id_attribute), uri=uri.lstrip("#"))
```
If you can load your doc and tweak this expression until it yields your element, I'll patch it up.

**Comment by nbastin** [comment]
You just need to add the literal text `xml:id` to the list in `self.id_attributes`.  This might not be the *right* thing, but it works.. :-)

**Comment by kislyuk** [comment]
OK, then please pass it in `verify(id_attributes=...)`.

The right thing would probably be to provide a namespace map somewhere when first loading the XML. Ugh. I'll think about including it in the default value.

**Comment by nbastin** [comment]
I think it's ok to include `xml:id` as it wouldn't be included in a namespace map anyhow, as it's special and defined in exactly that form in the standard (without needing to load a schema).

**Comment by kislyuk** [comment]
I think I agree with you, but as with most things about XML signature, the threat profile is pretty (over)complicated, so I want to think carefully about the implications, and whether `etree.load(nsmap={None: "xml"})` would do the trick without making any extra assumptions.
