### ISSUE TITLE
Syntax error during build of asn1.py

### ISSUE THREAD

**Issue by sailorfred** [kislyuk/signxml#57]
During a pip install on Ubuntu 14.04 shows this error during the build:

build/signxml/signxml/util/asn1.py'...
  File "..build/signxml/signxml/util/asn1.py", line 295
    self.value = 0L
                  ^
SyntaxError: invalid syntax

The build completes, but this is scary looking.

**Comment by kislyuk** [comment]
Thanks for reporting. I'm having a hard time understanding why the wheel build process picked up that file (it was a stray git-ignored file in my repo checkout), but I've removed it in v1.0.1, so you shouldn't see this error again. Please test.
