### ISSUE TITLE
Problematic distribution on windows (any hints on how to switch to pure python rsa libs)?

### ISSUE THREAD

**Issue by jankom** [kislyuk/signxml#8]
Hi,

I made a desktop app for signing eInvoices with SignXML. I was very happy with your module, because it solved my problem quickly and it's powerfull enough that I could switch to specific canonicalizsation and algorhitms that the specific eInvoice praxis required.

But most of users use windows. While I can elegantly install modules via pip and use them various app packagers didn't work. The submodules of cryptography couldn't install properly via packaged app for example with pyinstaller. The solution was to use pynsist, which installs regular python and copies modules, and then in instalation script run pip install for signXML and required modules. The solution is not ideal for end users because it also installs separate Python and Python Launcher, but it worked.

But now it seems some cryptography modules changed and the same instalation that worked doesn't work any more (app fails with error from cryptography.hazmat.primitives import interfaces
ImportError: cannot import name interfaces). I didn't yet figure out what is the problem. I thought the version of cryptography changed on pip but it doesn't seem to, if I install it manually in regular python both new and old versions work, with installation both of then don't.

Given the imperfect instalation and now that I can't even make it work I see two ways to solve this. Either I dump this and make app again in some other language or I can make SignXML work with pure python libs (like pyrsa), hence being able to package it with pyinstaller and removing the concrete problem I have now. Also, I don't need all the algo options SignXML offers but a smaller subset.

Do you have any oppinion on this? Could rewriting SignXML to use pure python work or are there any issues you think can't be solved without OpenSSL and other navice libs?

Is anyone else sucsessfully deploying SignXML application on Windows?

Thank for making this,
Jankos

**Comment by kislyuk** [comment]
I'm afraid I can't help you here. If you're having a problem building the cryptography module on Windows, you may have better luck using wheels (which are prebuilt), or bringing this up as an issue on the cryptography github repo.

I will not be switching away from cryptography and OpenSSL - the functions I use there are security-critical and well-tested. You're welcome to fork and try writing the relevant functionality yourself, but I think it's a complex task that would open up questions about security.

If a previous version of the module works reliably, then I advise that you stick with that version and paste here the specific errors that you experience.
